### ISSUE TITLE
Resurrect CI

### ISSUE THREAD

**Issue by dsyme** [fsprojects/FAKE#2607]
@sergey-tihon @yazeedobaid It looks like we need to resurrect CI

First, we should move from Azure Dev Ops to in-repo GitHub Actions.. The Azure DevOps azure-pipelines.yml from AzureDevOps is below. More will be needed

@matthid If you can give us any assistance that would be great.

```
steps:
- checkout: self
  clean: true
  lfs: true
- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.402'
  inputs:
    version: 2.1.402
# Paket - Setup CredMgr
- task: matthid.paket-private.c2aea098-6aab-4cd3-9a0c-57b074df3df5.setCredentialManager@0
  displayName: 'Setup Paket Credential Manager'
- bash: ./.paket/paket.exe update -v # contents of the script to run
  displayName: Paket update  # friendly name displayed in the UI
  workingDirectory: paket_cred  # initial working directory for the step
  #name: string  # identifier for this step (no spaces allowed)
  #failOnStderr: boolean  # if the script writes to stderr, should that be treated as the step failing?
  #condition: string
  #continueOnError: boolean  # 'true' if future steps should run even if this step fails; defaults to 'false'
  #enabled: boolean  # whether or not to run this step; defaults to 'true'
  #timeoutInMinutes: number
  #env: { string: string }  # list of environment variables to add
# Paket - Cleanup CredMgr
- task: matthid.paket-private.1c4d173c-798c-4636-a842-2da42eb2c20e.paketCredentialCleanup@0
  displayName: 'Cleanup Paket credential manager'
- bash: git clean -xdf .
  displayName: "Git Cleanup"
- bash: |
    if ./.paket/paket.exe update ; then
      echo "Expected paket to fail now."
      exit 1337 # contents of the script to run
    else
      echo "Ok paket failed as expected."
      exit 0
    fi
  displayName: Make sure paket update fails  # friendly name displayed in the UI
  workingDirectory: paket_cred  # initial working directory for the step
  failOnStderr: false
  
# Fake 5 runner
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute build.fsx (no args)'
# Fake 5 runner
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute scripts/build.fsx (without working dir)'
  inputs:
    FakeVersion: '5.6.1'
    FakeScript: 'scripts/build.fsx'
# Fake 5 runner
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute scripts/build.fsx (without working dir + args)'
  inputs:
    FakeVersion: '5.6.1'
    FakeScript: 'scripts/build.fsx'
    ScriptArguments: '-t AssumeScriptsBuild'
# Fake 5 runner
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute scripts/build.fsx (with . working dir)'
  inputs:
    FakeVersion: '5.6.1'
    FakeScript: 'scripts/build.fsx'
    WorkingDirectory: '.'
    ScriptArguments: '-t AssumeScriptsBuild'
# Paths are relative to project root by default
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute build.fsx (with scripts working dir)'
  inputs:
    FakeVersion: '5.6.1'
    FakeScript: 'build.fsx'
    WorkingDirectory: 'scripts'
    ScriptArguments: '-t AssumeRootBuild'
# Paths are relative to project root by default
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute scripts/build.fsx (with scripts working dir + full Command Line)'
  inputs:
    FakeVersion: '5.6.1'
    FakeScript: 'does not matter.fsx'
    WorkingDirectory: 'scripts'
    ScriptArguments: '-t does not matter'
    #PreventSecrets: true
    FakeArguments: 'run build.fsx -t AssumeScriptsBuild'
    #FailOnStdError: true
# Fake 5 runner
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute script/build.fsx (full args + no working dir)'
  inputs:
    FakeArguments: 'run scripts/build.fsx -t AssumeScriptsBuild'
# Fake 5 runner
- task: matthid.fake-build-private.dd88f622-7838-44dc-96d6-2372af78775b.FAKE5@1
  displayName: 'Execute script/build.fsx (full args + with working dir)'
  inputs:
    WorkingDirectory: 'scripts'
    FakeArguments: 'run build.fsx -t AssumeScriptsBuild'

```
